#!/usr/bin/env python3
"""Generate the two resources the desktop side needs from the Android resource tree.

PORTING.md §7.2.4 says the web panel "文案照搬" (copies the wording) and §7.2.6
lists i18n as a component to build. Neither section notices that the wording
already exists, translated, twelve times:

    res/values/strings.xml          1027 strings   (base)
    res/values-XX/strings.xml        955  strings  x 12 locales

That is ~11 500 translated strings, and the panel was about to be authored in
English only and translated from scratch. This script converts what is there.

Two outputs, because the extracted Kotlin and the web panel need different
shapes of the same data:

  1. `R.kt` — the resource-id object. Upstream code in the portable set refers
     to `R.string.foo` / `R.attr.ptAccent` / `R.color.…` in 129 places, and
     `R` is generated by the Android build. Off-device it has to be generated
     by something, and generating it from the XML is the only version that
     cannot drift: a resource added upstream appears here on the next run.

  2. `ui-web/i18n/<locale>.json` — a flat key/value map per locale, with the
     base string as the fallback for any key a locale does not translate.
     Emitted as data, not as JS, so the panel can lazy-load one locale.

Run:
    python3 pc/tools/gen_resources.py --res app/src/main/res \
        --r-kt pc/core/src/main/kotlin/com/playtranslate/R.kt \
        --i18n pc/ui-web/i18n
"""

from __future__ import annotations

import argparse
import json
import zlib
import re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

# `R.<type>.<name>`. Types not present in the XML are still emitted (empty
# object) so that a reference to one is a compile error about a missing member
# rather than about a missing object.
R_TYPES = {
    "string": "strings.xml",
    "color": "colors.xml",
    "dimen": "dimens.xml",
    "attr": "attrs.xml",
    "id": "ids.xml",
    "bool": "bools.xml",
}

# Locale directory -> BCP-47 tag the web panel will use.
LOCALE_DIRS = {
    "values-ar": "ar",
    "values-de": "de",
    "values-es": "es",
    "values-fr": "fr",
    "values-ja": "ja",
    "values-ko": "ko",
    "values-pt-rBR": "pt-BR",
    "values-ru": "ru",
    "values-th": "th",
    "values-tr": "tr",
    "values-vi": "vi",
    "values-zh-rCN": "zh-CN",
}

# Android string escapes that are not valid in JSON or in HTML text.
APOS = re.compile(r"\\(['\"@?])")
NL = re.compile(r"\\n")
HTML_ESCAPE = re.compile(r"<[^>]+>")


def parse_names(path: Path) -> list[str]:
    """Names of the top-level declarations in one values file."""
    if not path.is_file():
        return []
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        return []
    names: list[str] = []
    for child in root:
        n = child.get("name")
        if n:
            names.append(n)
    return names


def parse_strings(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        return {}
    out: dict[str, str] = {}
    for child in root:
        if child.tag not in ("string", "plurals"):
            continue
        name = child.get("name")
        if not name:
            continue
        if child.tag == "plurals":
            items = [i for i in child if i.tag == "item" and i.text]
            if items:
                out[name] = items[0].text or ""
            continue
        # A `<string>` may hold markup (b/i/u/annotation). Keep the text, drop
        # the markup, and flatten entities — the panel renders its own markup.
        text = "".join(child.itertext())
        text = APOS.sub(r"\1", text)
        text = NL.sub("\n", text)
        out[name] = text
    return out


def kotlin_ident(name: str) -> str:
    """Kotlin identifiers cannot start with a digit and cannot be keywords."""
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    if ident in {"object", "class", "interface", "val", "var", "fun", "is", "in", "when", "if", "for"}:
        ident = "`" + ident + "`"
    return ident


def gen_r_kt(res: Path, out: Path) -> dict[str, int]:
    lines = [
        "@file:Suppress(\"unused\", \"ConstPropertyName\", \"ObjectPropertyName\")",
        "",
        "package com.playtranslate",
        "",
        "/**",
        " * The resource ids, generated from `app/src/main/res/values/*.xml`.",
        " *",
        " * Do not edit. Regenerate with `python3 pc/tools/gen_resources.py`.",
        " *",
        " * The Android build generates this class; off-device it has to be generated",
        " * by something, and generating it from the same XML the Android build reads is",
        " * the only version that cannot drift. Values are opaque integers — the desktop",
        " * never resolves them the way Android does. The *strings* are resolved by the",
        " * web panel instead, from the JSON this script also writes, which is why this",
        " * object only has to exist, not to carry meaning.",
        " *",
        " * `R.style` carries no members on purpose: the extracted code names styles in",
        " * 11 places, and every one of them is a theme the desktop does not have. Leaving",
        " * the object empty turns each into a compile error at the call site, which is",
        " * where the decision about what replaces it belongs.",
        " */",
        "object R {",
    ]
    counts: dict[str, int] = {}
    for r_type, filename in R_TYPES.items():
        names = parse_names(res / "values" / filename)
        counts[r_type] = len(names)
        lines.append("")
        lines.append(f"    object {r_type} {{")
        for n in sorted(set(names)):
            # crc32, not hash(): Python's hash() is salted per process, so the
            # generated file would differ on every run and every commit would
            # show a thousand changed lines.
            lines.append(f"        const val {kotlin_ident(n)}: Int = {zlib.crc32(f'{r_type}/{n}'.encode()) % 0x7FFFFFFF}")
        lines.append("    }")
    lines.append("")
    lines.append("    /** Empty on purpose — see the class comment. */")
    lines.append("    object style")
    lines.append("")
    lines.append("    /** Referenced by the Anki card CSS. Rendered by the panel, not by Android. */")
    lines.append("    object drawable")
    lines.append("}")
    lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    return counts


def gen_i18n(res: Path, out_dir: Path) -> tuple[int, dict[str, int]]:
    base = parse_strings(res / "values" / "strings.xml")
    out_dir.mkdir(parents=True, exist_ok=True)
    # The base locale is also a file, so the panel has a complete fallback even
    # when a translation is missing a key.
    (out_dir / "en.json").write_text(
        json.dumps(base, ensure_ascii=False, indent=1, sort_keys=True) + "\n", encoding="utf-8")

    coverage: dict[str, int] = {}
    for dirname, tag in LOCALE_DIRS.items():
        trans = parse_strings(res / dirname / "strings.xml")
        merged = dict(base)
        merged.update({k: v for k, v in trans.items() if v})
        coverage[tag] = len(trans)
        (out_dir / f"{tag}.json").write_text(
            json.dumps(merged, ensure_ascii=False, indent=1, sort_keys=True) + "\n", encoding="utf-8")

    index = {
        "note": "Generated from app/src/main/res/values*/strings.xml by pc/tools/gen_resources.py. "
                "Do not edit by hand.",
        "base": "en",
        "locales": sorted(["en"] + list(LOCALE_DIRS.values())),
        "baseKeys": len(base),
        "translatedKeys": coverage,
    }
    (out_dir / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    return len(base), coverage


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--res", required=True)
    ap.add_argument("--r-kt", required=True)
    ap.add_argument("--i18n", required=True)
    args = ap.parse_args()

    res = Path(args.res)
    counts = gen_r_kt(res, Path(args.r_kt))
    base_n, coverage = gen_i18n(res, Path(args.i18n))

    print(f"R.kt: " + ", ".join(f"{k}={v}" for k, v in counts.items()))
    print(f"i18n: base={base_n} keys, {len(coverage)} locales "
          f"({sum(coverage.values())} translated entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
